// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYcCC-tZH7wt6KXMEkmdP_4hvBxyWo27E',
    appId: '1:282311074622:web:5c26cf2eaec12b574b826f',
    messagingSenderId: '282311074622',
    projectId: 'mymbg-7cfd1',
    authDomain: 'mymbg-7cfd1.firebaseapp.com',
    storageBucket: 'mymbg-7cfd1.firebasestorage.app',
    measurementId: 'G-F5CJDHM7YF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFJ8DxgYAM02jR8y5MJ_4cQnJs0OmB188',
    appId: '1:282311074622:android:add85310ff3b51254b826f',
    messagingSenderId: '282311074622',
    projectId: 'mymbg-7cfd1',
    storageBucket: 'mymbg-7cfd1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx_AxAjk9CtP_VXmXmW0jGjn4ussKuteg',
    appId: '1:282311074622:ios:22279c195f9a30204b826f',
    messagingSenderId: '282311074622',
    projectId: 'mymbg-7cfd1',
    storageBucket: 'mymbg-7cfd1.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiPendataanMbg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx_AxAjk9CtP_VXmXmW0jGjn4ussKuteg',
    appId: '1:282311074622:ios:22279c195f9a30204b826f',
    messagingSenderId: '282311074622',
    projectId: 'mymbg-7cfd1',
    storageBucket: 'mymbg-7cfd1.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiPendataanMbg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYcCC-tZH7wt6KXMEkmdP_4hvBxyWo27E',
    appId: '1:282311074622:web:b4b7ded7cdebb7144b826f',
    messagingSenderId: '282311074622',
    projectId: 'mymbg-7cfd1',
    authDomain: 'mymbg-7cfd1.firebaseapp.com',
    storageBucket: 'mymbg-7cfd1.firebasestorage.app',
    measurementId: 'G-5ZMS8292GR',
  );
}
